# Dependencies
markdown:         redcarpet
highlighter:         pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ryan Ewing
tagline:          'tinkerer'
description:      'Personal website of Ryan Ewing'
url:              http://ryanewing.github.io/

author:
  name:           'Ryan Ewing'
  url:            https://twitter.com/ryanewing
  email:          ewing.ryan@gmail.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  me:           https://github.com/ryanewing/
